CREATE EXTENSION vector;
SELECT * FROM pg_extension;

CREATE TABLE documents (
    -- bigint is better for long-term growth
    -- GENERATED BY DEFAULT allows us to manually update it during re-sequencing
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT,
    embedding VECTOR(384)
);



INSERT INTO documents (content, embedding)
VALUES (
    'Patient has leg pain',
    (
        SELECT array_agg(random())::vector
        FROM generate_series(1,384)
    )
);

-- Replace 'documents_id_seq' with your actual sequence name. 
-- Usually, it is: [table_name]_[column_name]_seq
-- This forces the counter back to 1
ALTER SEQUENCE documents_id_seq RESTART WITH 1;
SELECT * FROM documents;
DELETE FROM documents 
WHERE id BETWEEN 6 AND 28;